import { pb } from '@/models/flamingoProtobufTypes.ts';

/*
request_header_proto = {
	1: ("version", String()),
	2: ("service", String()),
	3: ("rpcthing", String()),
	4: ("authenticationTicket", String()),
	6: ("unk0", Varint()),
	7: ("unk1", Varint()),
	9: ("clide", String())
}*/
export const RequestHeaderProtobuf = pb.root({
    authenticationTicket: [
        4,
        pb.string(),
        { optional: true, repeatable: false },
    ],
    clide: [9, pb.string(), { optional: true, repeatable: false }],
    rpc: [3, pb.string(), { optional: false, repeatable: false }],
    service: [2, pb.string(), { optional: false, repeatable: false }],
    unknown1: [6, pb.varint(), { optional: true, repeatable: false }],
    unknown2: [7, pb.varint(), { optional: true, repeatable: false }],
    version: [1, pb.string(), { optional: true, repeatable: false }],
});

export const ResponseHeaderProtobuf = pb.root({
    gzipped: [7, pb.varint(), { optional: true, repeatable: false }],
    id: [1, pb.string(), { optional: false, repeatable: false }],
    rpc: [3, pb.string(), { optional: true, repeatable: false }],
    timestamp: [2, pb.varint(), { optional: false, repeatable: false }],
});

export const AllInOneLoginRequestProtobuf = pb.root({
    allInOneLogin: [
        112,
        pb.packed({
            cinta: [3, pb.string(), { optional: true, repeatable: false }],
            unknown1: [15, pb.varint(), { optional: false, repeatable: false }],
        }),
        { optional: false, repeatable: false },
    ],
    appVersion: [7, pb.string(), { optional: false, repeatable: false }],
    id: [1, pb.varint(), { optional: false, repeatable: false }],
    timestamp: [11, pb.varint(), { optional: false, repeatable: false }],
    type: [2, pb.varint(), { optional: false, repeatable: false }],
});

export const AllInOneLoginResponseProtobuf = pb.root({
    allInOneLogin: [
        112,
        pb.packed({
            authenticationTicket: [
                1,
                pb.string(),
                { optional: false, repeatable: false },
            ],
            cinta: [4, pb.string(), { optional: true, repeatable: false }],
            clide: [2, pb.string(), { optional: true, repeatable: false }],
            expiryTimestamp: [
                3,
                pb.varint(),
                { optional: false, repeatable: false },
            ],
        }),
        { optional: false, repeatable: false },
    ],
    clide: [10, pb.string(), { optional: true, repeatable: false }],
    id: [1, pb.varint(), { optional: false, repeatable: false }],
    status: [3, pb.varint(), { optional: false, repeatable: false }],
    type: [2, pb.varint(), { optional: false, repeatable: false }],
});

export const CMSRequestProtobuf = pb.root({
    appVersion: [2, pb.string(), { optional: false, repeatable: false }],
    authenticationTicket: [
        6,
        pb.string(),
        { optional: false, repeatable: false },
    ],
    id: [1, pb.varint(), { optional: false, repeatable: false }],
    timestamp: [3, pb.varint(), { optional: false, repeatable: false }],
    unknown1: [4, pb.string(), { optional: false, repeatable: false }],
    versions: [
        5,
        pb.packed({
            data: [
                4,
                pb.packed({
                    versions: [
                        1,
                        pb.packed({
                            locale: [
                                7,
                                pb.string(),
                                { optional: true, repeatable: false },
                            ],
                            localHash: [
                                3,
                                pb.string(),
                                { optional: true, repeatable: false },
                            ],
                            localVersion: [
                                2,
                                pb.string(),
                                { optional: true, repeatable: false },
                            ],
                            name: [
                                1,
                                pb.string(),
                                { optional: false, repeatable: false },
                            ],
                        }),
                        { optional: false, repeatable: true },
                    ],
                }),
                { optional: false, repeatable: false },
            ],
            unknown0: [1, pb.varint(), { optional: true, repeatable: false }],
            unknown1: [2, pb.string(), { optional: true, repeatable: false }],
            unknown2: [3, pb.varint(), { optional: true, repeatable: false }],
        }),
        { optional: false, repeatable: false },
    ],
});

export const CMSResponseProtobuf = pb.root({
    id: [1, pb.varint(), { optional: false, repeatable: false }],
    timestamp: [2, pb.varint(), { optional: false, repeatable: false }],
    unknown4: [4, pb.string(), { optional: true, repeatable: false }],
    versions: [
        5,
        pb.packed({
            data: [
                5,
                pb.packed({
                    unknown1: [
                        2,
                        pb.packed({}),
                        { optional: true, repeatable: false },
                    ],
                    versions: [
                        1,
                        pb.packed({
                            hash: [
                                3,
                                pb.string(),
                                { optional: false, repeatable: false },
                            ],
                            name: [
                                1,
                                pb.string(),
                                { optional: false, repeatable: false },
                            ],
                            url: [
                                5,
                                pb.string(),
                                { optional: false, repeatable: false },
                            ],
                            version: [
                                2,
                                pb.string(),
                                { optional: false, repeatable: false },
                            ],
                        }),
                        { optional: false, repeatable: true },
                    ],
                }),
                { optional: false, repeatable: false },
            ],
            unknown0: [1, pb.varint(), { optional: true, repeatable: false }],
            unknown1: [2, pb.string(), { optional: true, repeatable: false }],
            unknown2: [3, pb.varint(), { optional: true, repeatable: false }],
            unknown3: [4, pb.string(), { optional: true, repeatable: false }],
        }),
        { optional: false, repeatable: false },
    ],
});

export const RewardProtobuf = pb.root({
    reward: [
        2,
        pb.packed({
            gemCount: [2, pb.varint(), { optional: false, repeatable: false }],
            type: [1, pb.varint(), { optional: false, repeatable: false }], // 11=unlimited_play, 8=cards, 2=gems, 6=song
        }),
        { optional: false, repeatable: false },
    ],
    rewardType: [1, pb.varint(), { optional: false, repeatable: false }],
});

export const GameConfigProtobuf = pb.root({
    // unknown120: [110, pb.buffer(), { optional: true, repeatable: false }],
    // unknown121: [115, pb.buffer(), { optional: true, repeatable: false }],
    bundleIAPs: [
        116,
        pb.array(
            pb.root({
                disabled: [
                    5,
                    pb.varint(),
                    { optional: false, repeatable: false },
                ],
                id: [1, pb.string(), { optional: false, repeatable: false }],
                name: [3, pb.string(), { optional: false, repeatable: false }],
                price: [6, pb.varint(), { optional: false, repeatable: false }],
                sku: [2, pb.string(), { optional: false, repeatable: false }],
            }),
        ),
        { optional: false, repeatable: false },
    ],
    categories: [
        102,
        pb.array(
            pb.root({
                checksum: [
                    8,
                    pb.string(),
                    { optional: true, repeatable: false },
                ],
                color: [8, pb.string(), { optional: true, repeatable: false }],
                filter: [
                    12,
                    pb.string(),
                    { optional: false, repeatable: false },
                ],
                genreId: [
                    6,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                hash: [10, pb.string(), { optional: true, repeatable: false }],
                id: [1, pb.varint(), { optional: false, repeatable: false }],
                name: [5, pb.string(), { optional: false, repeatable: false }],
                unknown1: [
                    9,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown2: [
                    11,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown3: [
                    14,
                    pb.string(),
                    { optional: true, repeatable: false },
                ],
                unknown4: [
                    13,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
            }),
        ),
        { optional: false, repeatable: false },
    ],
    // unknown117: [105, pb.buffer(), { optional: true, repeatable: false }],
    // unknown118: [107, pb.buffer(), { optional: true, repeatable: false }],
    effects: [
        109,
        pb.array(
            pb.root({
                id: [1, pb.varint(), { optional: false, repeatable: false }],
                internalId: [
                    7,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                name: [2, pb.string(), { optional: true, repeatable: false }],
                unknown1: [
                    3,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
            }),
        ),
        { optional: false, repeatable: false },
    ],
    gamepasses: [
        117,
        pb.array(
            pb.root({
                id: [1, pb.string(), { optional: false, repeatable: false }],
                reward: [
                    7,
                    pb.packed({
                        reward: [
                            1,
                            pb.array(
                                pb.root({
                                    reward: [
                                        2,
                                        pb.packed({
                                            data: [
                                                2,
                                                pb.varint(),
                                                {
                                                    optional: true,
                                                    repeatable: false,
                                                },
                                            ],
                                            type: [
                                                1,
                                                pb.varint(),
                                                {
                                                    optional: true,
                                                    repeatable: false,
                                                },
                                            ],
                                        }),
                                        { optional: false, repeatable: false },
                                    ],
                                    rewardType: [
                                        1,
                                        pb.varint(),
                                        { optional: false, repeatable: false },
                                    ],
                                }),
                            ),
                            { optional: false, repeatable: false },
                        ],
                    }),
                    { optional: false, repeatable: false },
                ],
                tier: [6, pb.string(), { optional: true, repeatable: false }],
            }),
        ),
        { optional: false, repeatable: false },
    ],
    loadingTips: [
        1017,
        pb.packed({
            tips: [2, pb.string(), { optional: false, repeatable: true }],
        }),
        { optional: false, repeatable: false },
    ],
    lootBoxes: [
        119,
        pb.array(
            pb.root({
                id: [1, pb.varint(), { optional: false, repeatable: false }],
                name: [2, pb.string(), { optional: false, repeatable: false }],
                unknown1: [
                    37,
                    pb.string(),
                    { optional: true, repeatable: false },
                ],
                unknown2: [
                    18,
                    pb.packed({
                        unknown1: [
                            1,
                            pb.array(
                                pb.root({
                                    unknown1: [
                                        1,
                                        pb.buffer(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown2: [
                                        2,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown3: [
                                        3,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown4: [
                                        4,
                                        pb.string(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown5: [
                                        6,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown6: [
                                        19,
                                        pb.buffer(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown7: [
                                        11,
                                        pb.buffer(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown8: [
                                        20,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown9: [
                                        15,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                    unknown10: [
                                        17,
                                        pb.varint(),
                                        { optional: true, repeatable: false },
                                    ],
                                }),
                            ),
                            { optional: false, repeatable: false },
                        ],
                        unknown2: [
                            6,
                            pb.varint(),
                            { optional: false, repeatable: false },
                        ],
                        unknown3: [
                            7,
                            pb.varint(),
                            { optional: true, repeatable: false },
                        ],
                        unknown4: [
                            8,
                            pb.varint(),
                            { optional: true, repeatable: false },
                        ],
                        unknown5: [
                            9,
                            pb.varint(),
                            { optional: true, repeatable: false },
                        ],
                    }),
                    { optional: true, repeatable: false },
                ],
                unknown3: [
                    4,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown4: [
                    22,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown5: [
                    41,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown6: [
                    24,
                    pb.string(),
                    { optional: true, repeatable: false },
                ],
                unknown7: [
                    25,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
                unknown8: [
                    38,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
                unknown9: [
                    28,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
                unknown10: [
                    29,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown11: [
                    30,
                    pb.varint(),
                    { optional: true, repeatable: false },
                ],
                unknown12: [
                    33,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
                unknown13: [
                    34,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
                unknown14: [
                    42,
                    pb.buffer(),
                    { optional: true, repeatable: false },
                ],
            }),
        ),
        { optional: true, repeatable: false },
    ],
    shopItems: [121, pb.buffer(), { optional: true, repeatable: false }],
    unknown1: [
        1014,
        pb.packed({
            unknown1: [3, pb.float(), { optional: false, repeatable: false }],
            unknown2: [5, pb.varint(), { optional: false, repeatable: false }],
            unknown3: [6, pb.varint(), { optional: false, repeatable: false }],
            unknown4: [7, pb.varint(), { optional: false, repeatable: false }],
        }),
        { optional: true, repeatable: false },
    ],
    unknown2: [1016, pb.buffer(), { optional: true, repeatable: false }],
    unknown3: [1018, pb.buffer(), { optional: true, repeatable: false }],
    unknown4: [1019, pb.buffer(), { optional: true, repeatable: false }],
    unknown5: [1020, pb.buffer(), { optional: true, repeatable: false }],
    unknown6: [1021, pb.buffer(), { optional: true, repeatable: false }],
    unknown7: [1026, pb.buffer(), { optional: true, repeatable: false }],
    unknown8: [1028, pb.buffer(), { optional: true, repeatable: false }],
    unknown9: [1031, pb.buffer(), { optional: true, repeatable: false }],
    unknown10: [1037, pb.buffer(), { optional: true, repeatable: false }],
    unknown11: [1039, pb.buffer(), { optional: true, repeatable: false }],
    unknown12: [1047, pb.buffer(), { optional: true, repeatable: false }],
    unknown13: [1048, pb.buffer(), { optional: true, repeatable: false }],
    unknown14: [1055, pb.buffer(), { optional: true, repeatable: false }],
    unknown15: [1059, pb.buffer(), { optional: true, repeatable: false }],
    unknown16: [1061, pb.buffer(), { optional: true, repeatable: false }],
    unknown17: [1062, pb.buffer(), { optional: true, repeatable: false }],
    unknown18: [1063, pb.buffer(), { optional: true, repeatable: false }],
    unknown19: [1064, pb.buffer(), { optional: true, repeatable: false }],
    unknown20: [1065, pb.buffer(), { optional: true, repeatable: false }],
    unknown21: [1066, pb.buffer(), { optional: true, repeatable: false }],
    unknown22: [1068, pb.buffer(), { optional: true, repeatable: false }],
    unknown23: [1069, pb.buffer(), { optional: true, repeatable: false }],
    unknown24: [1070, pb.buffer(), { optional: true, repeatable: false }],
    unknown25: [1071, pb.buffer(), { optional: true, repeatable: false }],
    unknown26: [1072, pb.buffer(), { optional: true, repeatable: false }],
    unknown27: [1074, pb.buffer(), { optional: true, repeatable: false }],
    unknown28: [1075, pb.buffer(), { optional: true, repeatable: false }],
    unknown29: [1076, pb.buffer(), { optional: true, repeatable: false }],
    unknown30: [1077, pb.buffer(), { optional: true, repeatable: false }],
    unknown31: [1079, pb.buffer(), { optional: true, repeatable: false }],
    unknown32: [1080, pb.buffer(), { optional: true, repeatable: false }],
    unknown33: [1081, pb.buffer(), { optional: true, repeatable: false }],
    unknown34: [1082, pb.buffer(), { optional: true, repeatable: false }],
    unknown35: [1083, pb.buffer(), { optional: true, repeatable: false }],
    unknown36: [1084, pb.buffer(), { optional: true, repeatable: false }],
    unknown37: [1085, pb.buffer(), { optional: true, repeatable: false }],
    unknown38: [1086, pb.buffer(), { optional: true, repeatable: false }],
    unknown39: [1087, pb.buffer(), { optional: true, repeatable: false }],
    unknown40: [1088, pb.buffer(), { optional: true, repeatable: false }],
    unknown41: [1089, pb.buffer(), { optional: true, repeatable: false }],
    unknown42: [1090, pb.buffer(), { optional: true, repeatable: false }],
    unknown43: [1091, pb.buffer(), { optional: true, repeatable: false }],
    unknown44: [1092, pb.buffer(), { optional: true, repeatable: false }],
    unknown45: [1093, pb.buffer(), { optional: true, repeatable: false }],
    // unknown46: [1094, pb.buffer(), { optional: true, repeatable: false }],
    unknown47: [1095, pb.buffer(), { optional: true, repeatable: false }],
    unknown48: [1096, pb.buffer(), { optional: true, repeatable: false }],
    unknown49: [1097, pb.buffer(), { optional: true, repeatable: false }],
    unknown50: [1098, pb.buffer(), { optional: true, repeatable: false }],
    unknown51: [1099, pb.buffer(), { optional: true, repeatable: false }],
    unknown52: [1100, pb.buffer(), { optional: true, repeatable: false }],
    unknown53: [1101, pb.buffer(), { optional: true, repeatable: false }],
    unknown54: [1102, pb.buffer(), { optional: true, repeatable: false }],
    unknown55: [1103, pb.buffer(), { optional: true, repeatable: false }],
    unknown56: [1104, pb.buffer(), { optional: true, repeatable: false }],
    unknown57: [1105, pb.buffer(), { optional: true, repeatable: false }],
    unknown58: [1106, pb.buffer(), { optional: true, repeatable: false }],
    // unknown59: [1107, pb.buffer(), { optional: true, repeatable: false }],
    // unknown60: [1108, pb.buffer(), { optional: true, repeatable: false }],
    // unknown61: [1109, pb.buffer(), { optional: true, repeatable: false }],
    unknown62: [1110, pb.buffer(), { optional: true, repeatable: false }],
    unknown63: [1111, pb.buffer(), { optional: true, repeatable: false }],
    unknown64: [1112, pb.buffer(), { optional: true, repeatable: false }],
    unknown65: [1113, pb.buffer(), { optional: true, repeatable: false }],
    // unknown66: [1114, pb.buffer(), { optional: true, repeatable: false }],
    // unknown67: [1115, pb.buffer(), { optional: true, repeatable: false }],
    unknown68: [1116, pb.buffer(), { optional: true, repeatable: false }],
    // unknown69: [1117, pb.buffer(), { optional: true, repeatable: false }],
    unknown70: [1118, pb.buffer(), { optional: true, repeatable: false }],
    unknown71: [1119, pb.buffer(), { optional: true, repeatable: false }],
    unknown72: [1120, pb.buffer(), { optional: true, repeatable: false }],
    unknown73: [1121, pb.buffer(), { optional: true, repeatable: false }],
    unknown74: [1122, pb.buffer(), { optional: true, repeatable: false }],
    unknown75: [1123, pb.buffer(), { optional: true, repeatable: false }],
    unknown76: [1124, pb.buffer(), { optional: true, repeatable: false }],
    unknown77: [1125, pb.buffer(), { optional: true, repeatable: false }],
    // unknown78: [1126, pb.buffer(), { optional: true, repeatable: false }],
    // unknown79: [1127, pb.buffer(), { optional: true, repeatable: false }],
    // unknown80: [1128, pb.buffer(), { optional: true, repeatable: false }],
    // unknown81: [1129, pb.buffer(), { optional: true, repeatable: false }],
    // unknown82: [1130, pb.buffer(), { optional: true, repeatable: false }],
    // unknown83: [1131, pb.buffer(), { optional: true, repeatable: false }],
    // unknown84: [1132, pb.buffer(), { optional: true, repeatable: false }],
    // unknown85: [1133, pb.buffer(), { optional: true, repeatable: false }],
    // unknown86: [1134, pb.buffer(), { optional: true, repeatable: false }],
    // unknown87: [1135, pb.buffer(), { optional: true, repeatable: false }],
    // unknown88: [1136, pb.buffer(), { optional: true, repeatable: false }],
    // unknown89: [1137, pb.buffer(), { optional: true, repeatable: false }],
    // unknown90: [1138, pb.buffer(), { optional: true, repeatable: false }],
    // unknown91: [1139, pb.buffer(), { optional: true, repeatable: false }],
    // unknown92: [1140, pb.buffer(), { optional: true, repeatable: false }],
    // unknown93: [1141, pb.buffer(), { optional: true, repeatable: false }],
    // unknown94: [1142, pb.buffer(), { optional: true, repeatable: false }],
    // unknown95: [1143, pb.buffer(), { optional: true, repeatable: false }],
    // unknown96: [1144, pb.buffer(), { optional: true, repeatable: false }],
    // unknown97: [1145, pb.buffer(), { optional: true, repeatable: false }],
    // unknown98: [1146, pb.buffer(), { optional: true, repeatable: false }],
    // unknown99: [1147, pb.buffer(), { optional: true, repeatable: false }],
    // unknown100: [1148, pb.buffer(), { optional: true, repeatable: false }],
    // unknown101: [1149, pb.buffer(), { optional: true, repeatable: false }],
    // unknown102: [1150, pb.buffer(), { optional: true, repeatable: false }],
    // unknown103: [1151, pb.buffer(), { optional: true, repeatable: false }],
    // unknown104: [1152, pb.buffer(), { optional: true, repeatable: false }],
    // unknown105: [1153, pb.buffer(), { optional: true, repeatable: false }],
    // unknown106: [1154, pb.buffer(), { optional: true, repeatable: false }],
    // unknown107: [1155, pb.buffer(), { optional: true, repeatable: false }],
    // unknown108: [1156, pb.buffer(), { optional: true, repeatable: false }],
    // unknown109: [1157, pb.buffer(), { optional: true, repeatable: false }],
    // unknown110: [1158, pb.buffer(), { optional: true, repeatable: false }],
    // unknown111: [1159, pb.buffer(), { optional: true, repeatable: false }],
    unknown112: [16, pb.buffer(), { optional: true, repeatable: true }],
    unknown113: [31, pb.buffer(), { optional: true, repeatable: true }],
    unknown114: [74, pb.buffer(), { optional: true, repeatable: false }],
    unknown115: [99, pb.buffer(), { optional: true, repeatable: false }],
    unknown126: [124, pb.buffer(), { optional: true, repeatable: false }],
    unknown127: [141, pb.buffer(), { optional: true, repeatable: false }],
    unknown128: [111, pb.buffer(), { optional: true, repeatable: false }],
    unknown129: [120, pb.buffer(), { optional: true, repeatable: false }],
    unknown130: [122, pb.buffer(), { optional: true, repeatable: false }],
    unknown131: [123, pb.buffer(), { optional: true, repeatable: false }],
    unknown132: [125, pb.buffer(), { optional: true, repeatable: false }],
    unknown133: [126, pb.buffer(), { optional: true, repeatable: false }],
    unknown134: [127, pb.buffer(), { optional: true, repeatable: false }],
    unknown135: [128, pb.buffer(), { optional: true, repeatable: false }],
    unknown136: [129, pb.buffer(), { optional: true, repeatable: false }],
    unknown137: [130, pb.buffer(), { optional: true, repeatable: false }],
    unknown138: [131, pb.buffer(), { optional: true, repeatable: false }],
    unknown139: [143, pb.buffer(), { optional: true, repeatable: false }],
    unknown140: [144, pb.buffer(), { optional: true, repeatable: false }],
    unknown141: [145, pb.buffer(), { optional: true, repeatable: false }],
    unknown142: [146, pb.buffer(), { optional: true, repeatable: false }],
    // unknown143: [148, pb.buffer(), { optional: true, repeatable: false }],
    unknown144: [149, pb.buffer(), { optional: true, repeatable: false }],
    unknown145: [150, pb.buffer(), { optional: true, repeatable: false }],
    unknown146: [151, pb.buffer(), { optional: true, repeatable: false }],
    unknown147: [152, pb.buffer(), { optional: true, repeatable: false }],
    // unknown148: [153, pb.buffer(), { optional: true, repeatable: false }],
    unknown149: [154, pb.buffer(), { optional: true, repeatable: false }],
    unknown150: [155, pb.buffer(), { optional: true, repeatable: false }],
    unknown151: [156, pb.buffer(), { optional: true, repeatable: false }],
    unknown152: [157, pb.buffer(), { optional: true, repeatable: false }],
    unknown153: [158, pb.buffer(), { optional: true, repeatable: false }],
    unknown154: [159, pb.buffer(), { optional: true, repeatable: false }],
    // unknown155: [160, pb.buffer(), { optional: true, repeatable: false }],
    // unknown156: [161, pb.buffer(), { optional: true, repeatable: false }],
    // unknown157: [162, pb.buffer(), { optional: true, repeatable: false }],
    // unknown158: [163, pb.buffer(), { optional: true, repeatable: false }],
    unknown159: [133, pb.buffer(), { optional: true, repeatable: false }],
    unknown160: [134, pb.buffer(), { optional: true, repeatable: false }],
    unknown161: [135, pb.buffer(), { optional: true, repeatable: false }],
    // unknown162: [136, pb.buffer(), { optional: true, repeatable: false }],
    // unknown163: [137, pb.buffer(), { optional: true, repeatable: false }],
    unknown164: [138, pb.buffer(), { optional: true, repeatable: false }],
    unknown165: [139, pb.buffer(), { optional: true, repeatable: false }],
    unknown166: [140, pb.buffer(), { optional: true, repeatable: false }],
    // unknown167: [141, pb.buffer(), { optional: true, repeatable: false }],
    unknown168: [142, pb.buffer(), { optional: true, repeatable: false }],
    // unknown169: [143, pb.buffer(), { optional: true, repeatable: false }],
    // unknown170: [144, pb.buffer(), { optional: true, repeatable: false }],
    // unknown171: [145, pb.buffer(), { optional: true, repeatable: false }],
    // unknown172: [146, pb.buffer(), { optional: true, repeatable: false }],
    unknown173: [147, pb.buffer(), { optional: true, repeatable: false }],
    // unknown174: [148, pb.buffer(), { optional: true, repeatable: false }],
    // unknown175: [149, pb.buffer(), { optional: true, repeatable: false }],
    // unknown176: [150, pb.buffer(), { optional: true, repeatable: false }],
    // unknown177: [151, pb.buffer(), { optional: true, repeatable: false }],
    // unknown178: [152, pb.buffer(), { optional: true, repeatable: false }],
    // unknown179: [153, pb.buffer(), { optional: true, repeatable: false }],
    // unknown180: [154, pb.buffer(), { optional: true, repeatable: false }],
    // unknown181: [155, pb.buffer(), { optional: true, repeatable: false }],
    // unknown182: [156, pb.buffer(), { optional: true, repeatable: false }],
    // unknown183: [157, pb.buffer(), { optional: true, repeatable: false }],
    // unknown184: [158, pb.buffer(), { optional: true, repeatable: false }],
    // unknown185: [159, pb.buffer(), { optional: true, repeatable: false }],
    // unknown186: [160, pb.buffer(), { optional: true, repeatable: false }],
    // unknown187: [161, pb.buffer(), { optional: true, repeatable: false }],
    // unknown188: [162, pb.buffer(), { optional: true, repeatable: false }],
    // unknown189: [163, pb.buffer(), { optional: true, repeatable: false }],
    // unknown190: [164, pb.buffer(), { optional: true, repeatable: false }],
    // unknown191: [165, pb.buffer(), { optional: true, repeatable: false }],
    // unknown192: [166, pb.buffer(), { optional: true, repeatable: false }],
    // unknown193: [167, pb.buffer(), { optional: true, repeatable: false }],
    // unknown194: [168, pb.buffer(), { optional: true, repeatable: false }],
    // unknown195: [169, pb.buffer(), { optional: true, repeatable: false }],
    unknown196: [170, pb.buffer(), { optional: true, repeatable: false }],
    unknown197: [171, pb.buffer(), { optional: true, repeatable: false }],
    unknown198: [172, pb.buffer(), { optional: true, repeatable: false }],
    unknown199: [173, pb.buffer(), { optional: true, repeatable: false }],
    unknown200: [174, pb.buffer(), { optional: true, repeatable: false }],
    unknown201: [175, pb.buffer(), { optional: true, repeatable: false }],
    // unknown202: [176, pb.buffer(), { optional: true, repeatable: false }],
    unknown203: [177, pb.buffer(), { optional: true, repeatable: false }],
    // unknown204: [178, pb.buffer(), { optional: true, repeatable: false }],
    unknown205: [179, pb.buffer(), { optional: true, repeatable: false }],
    // unknown206: [180, pb.buffer(), { optional: true, repeatable: false }],
    unknown207: [181, pb.buffer(), { optional: true, repeatable: false }],
    unknown208: [182, pb.buffer(), { optional: true, repeatable: false }],
    unknown209: [183, pb.buffer(), { optional: true, repeatable: false }],
    unknown210: [184, pb.buffer(), { optional: true, repeatable: false }],
    unknown211: [185, pb.buffer(), { optional: true, repeatable: false }],
    unknown212: [186, pb.buffer(), { optional: true, repeatable: false }],
    // unknown213: [187, pb.buffer(), { optional: true, repeatable: false }],
    unknown214: [188, pb.buffer(), { optional: true, repeatable: false }],
    // unknown215: [189, pb.buffer(), { optional: true, repeatable: false }],
    // unknown216: [190, pb.buffer(), { optional: true, repeatable: false }],
    // unknown217: [191, pb.buffer(), { optional: true, repeatable: false }],
    // unknown218: [192, pb.buffer(), { optional: true, repeatable: false }],
    // unknown219: [193, pb.buffer(), { optional: true, repeatable: false }],
    unknown220: [194, pb.buffer(), { optional: true, repeatable: false }],
    unknown221: [195, pb.buffer(), { optional: true, repeatable: false }],
    unknown222: [196, pb.buffer(), { optional: true, repeatable: false }],
    unknown223: [197, pb.buffer(), { optional: true, repeatable: false }],
    unknown224: [198, pb.buffer(), { optional: true, repeatable: false }],
    unknown225: [199, pb.buffer(), { optional: true, repeatable: false }],
    // unknown226: [200, pb.buffer(), { optional: true, repeatable: false }],
    unknown227: [201, pb.buffer(), { optional: true, repeatable: false }],
    unknown228: [202, pb.buffer(), { optional: true, repeatable: false }],
    unknown229: [203, pb.buffer(), { optional: true, repeatable: false }],
    unknown230: [204, pb.buffer(), { optional: true, repeatable: false }],
    unknown231: [205, pb.buffer(), { optional: true, repeatable: false }],
    // unknown232: [206, pb.buffer(), { optional: true, repeatable: false }],
    unknown233: [207, pb.buffer(), { optional: true, repeatable: false }],
    unknown234: [208, pb.buffer(), { optional: true, repeatable: false }],
    unknown235: [209, pb.buffer(), { optional: true, repeatable: false }],
    unknown236: [210, pb.buffer(), { optional: true, repeatable: false }],
    // unknown237: [211, pb.buffer(), { optional: true, repeatable: false }],
    unknown238: [212, pb.buffer(), { optional: true, repeatable: false }],
    // unknown239: [213, pb.buffer(), { optional: true, repeatable: false }],
    unknown240: [214, pb.buffer(), { optional: true, repeatable: false }],
    unknown241: [215, pb.buffer(), { optional: true, repeatable: false }],
    unknown242: [216, pb.buffer(), { optional: true, repeatable: false }],
    unknown243: [217, pb.buffer(), { optional: true, repeatable: false }],
    version: [1000, pb.string(), { optional: false, repeatable: false }],
    // unknown244: [218, pb.buffer(), { optional: true, repeatable: false }],
    // unknown245: [219, pb.buffer(), { optional: true, repeatable: false }],
    // unknown246: [220, pb.buffer(), { optional: true, repeatable: false }],

    // unknown1: [1018, pb.packed({}), { optional: true, repeatable: false }],
    // trackBeatmapPairs: [3, pb.packed({
    //     id: [1, pb.varint(), { optional: false, repeatable: false }],
    //     trackId: [21, pb.varint(), { optional: false, repeatable: false }],
    //     description: [37, pb.string(), { optional: false, repeatable: false }],
    //     beatmapId: [46, pb.varint(), { optional: false, repeatable: false }],
    // }), { optional: false, repeatable: true }],
    // tracks: [25, pb.packed({
    //     id: [1, pb.varint(), { optional: false, repeatable: false }],
    //     hash: [19, pb.string(), { optional: false, repeatable: false }],
    //     someFile: [66, pb.string(), { optional: false, repeatable: false }],
    //     title: [76, pb.string(), { optional: false, repeatable: false }],
    //     artist: [77, pb.string(), { optional: false, repeatable: false }],
    // }), { optional: false, repeatable: true }],
    // unknown2: [88, pb.array(pb.packed({})), { optional: true, repeatable: false }],
    // categories: [102, pb.array(pb.packed({
    //     id: [1, pb.varint(), { optional: false, repeatable: false }],
    //     genreId: [10, pb.varint(), { optional: false, repeatable: false }],
    // })), { optional: false, repeatable: false }],
    // artists: [105, pb.array(pb.packed({
    //     id: [1, pb.varint(), { optional: false, repeatable: false }],
    //     name: [2, pb.string(), { optional: false, repeatable: false }],
    //     shortName: [3, pb.string(), { optional: true, repeatable: false }],
    // })), { optional: false, repeatable: false }],
    // emojis: [107, pb.array(pb.packed({})), { optional: false, repeatable: false }],
    // effects: [109, pb.array(pb.packed({})), { optional: false, repeatable: false }],
    // songTags: [110, pb.array(pb.packed({})), { optional: false, repeatable: false }],
    // banners: [115, pb.array(pb.packed({})), { optional: false, repeatable: false }],
    // bundleTiers: [116, pb.array(pb.packed({})), { optional: false, repeatable: false }],
    // bundleUnknown: [117, pb.array(pb.packed({
    //     unknown1: [7, pb.packed({
    //         unknown1: [1, pb.array(pb.embedded(RewardProtobuf)), { optional: false, repeatable: false }],
    //     }), { optional: false, repeatable: false }],
    // })), { optional: false, repeatable: false }],
});
